require("twitteR")
twitteR::setup_twitter_oauth(consumer_key = "CKuP9VUXhKVBmUR4MewoRxeoI", consumer_secret = "A4EohnxM0wZ45Bb12KW79IblyRp4nsbNU2HjtwnFrrutNRg2IB", access_token = "1405595161-sOkfPJofHrjMPlhF9h67E9hxcq3WrAHCqJBjxVl", access_secret = "EXjiyaCSac1iDXx6DRCalb0Of60gbsmTnsea3QY8kg8O8")
twitteR::searchTwitteR("influenza",n=1e4,since="2017-8-1",retryOnRateLimit = 1e3)
tweets <- twitteR::twListToDF(twitteR::searchTwitteR("influenza",n=1e4,since="2017-8-1",retryOnRateLimit = 1e3))
colnames(tweets)
write.xlsx(tweets, "tweets.xlsx", sheetName="Sheet1")
users <- twListToDF(lookupUsers(tweets$screenName))
colnames(users)
install.packages('ggmap')
subset_users <- subset(users, !(users$location == ""))
subset_users$location <- stri_conv(subset_users$location, to="ascii")
library(ggmap)
#geocode(subset_users$location[0:2400])

