require("twitteR")
library(stringi)
library(xlsx)
twitteR::setup_twitter_oauth(consumer_key = "CKuP9VUXhKVBmUR4MewoRxeoI", consumer_secret = "A4EohnxM0wZ45Bb12KW79IblyRp4nsbNU2HjtwnFrrutNRg2IB", access_token = "1405595161-sOkfPJofHrjMPlhF9h67E9hxcq3WrAHCqJBjxVl", access_secret = "EXjiyaCSac1iDXx6DRCalb0Of60gbsmTnsea3QY8kg8O8")
#twitteR::searchTwitteR("influenza+flu",n=2e4,since="2017-8-1",retryOnRateLimit = 1e3)
tweets <- twitteR::twListToDF(twitteR::searchTwitteR("influenza+flu",n=4676,since="2017-8-1",retryOnRateLimit = 1e3))
colnames(tweets)
write.xlsx(tweets, "tweets1.xlsx", sheetName="Sheet1")
users <- twListToDF(lookupUsers(tweets$screenName))
colnames(users)
install.packages('ggmap')
write.xlsx(users, "users1.xlsx", sheetName="Sheet1")
subset_users <- subset(users, !(users$location == ""))
subset_users$location <- stri_conv(subset_users$location, to="ascii")
library(ggmap)
geocodes <- geocode(subset_users$location[0:2499])
#geocodes <- rbind(geocodes,geocode(subset_users$location[2500:4999]))
#geocodes <- rbind(geocodes,geocode(subset_users$location[5000:7499]))
#geocodes <- rbind(geocodes,geocode(subset_users$location[7500:9999]))
